"""Model adapter and registry boundary."""

from face_of_agi.models.adapters import (
    GoalPredictionModel,
    ModelRegistry,
    OrchestratorAgentModel,
    WorldPredictionModel,
)
from face_of_agi.models.description import (
    OllamaDescriptionConfig,
    OpenAIDescriptionConfig,
)
from face_of_agi.models.goal import (
    GoalPredictionAdapter,
    GoalPredictionModel,
)
from face_of_agi.models.orchestrator_agent import (
    AgentProviderStep,
    AgentToolSpec,
    AgentTurnRequest,
    AgentToolRuntime,
    OllamaOrchestratorAgentConfig,
    OpenAIOrchestratorAgentConfig,
    OrchestratorAgentAdapter,
    OrchestratorAgentConfig,
    ProviderFunctionCall,
    ProviderToolFeedback,
)
from face_of_agi.models.world import (
    WorldPredictionAdapter,
    WorldPredictionModel,
)
from face_of_agi.models.updater import (
    AgentGameContextUpdateInput,
    AgentProgressFeedback,
    AgentGameContextUpdaterModel,
    ContextSegment,
    GeneralKnowledgeUpdateInput,
    GeneralKnowledgeUpdaterModel,
    GoalGameContextUpdateInput,
    GoalGameContextUpdaterModel,
    PromptUpdateProviderResponse,
    PromptUpdateRequest,
    PromptUpdateResult,
    PromptUpdaterAdapter,
    PromptUpdaterProvider,
    UpdaterContextTarget,
    UpdaterConfig,
    UpdaterOutputError,
    UpdaterRole,
    UpdaterTask,
    UpdaterTaskRegistry,
    WorldGameContextUpdateInput,
    WorldGameContextUpdaterModel,
    OpenAIUpdaterConfig,
    OllamaUpdaterConfig,
)
from face_of_agi.models.updater.providers import (
    ConfigurableUpdaterAdapter,
    HuggingFaceUpdaterAdapter,
    OllamaUpdaterAdapter,
    OpenAIUpdaterAdapter,
)

__all__ = [
    "AgentGameContextUpdateInput",
    "AgentProgressFeedback",
    "AgentGameContextUpdaterModel",
    "AgentProviderStep",
    "AgentToolSpec",
    "AgentTurnRequest",
    "ConfigurableUpdaterAdapter",
    "ContextSegment",
    "GeneralKnowledgeUpdateInput",
    "GeneralKnowledgeUpdaterModel",
    "GoalGameContextUpdateInput",
    "GoalGameContextUpdaterModel",
    "GoalPredictionAdapter",
    "GoalPredictionModel",
    "AgentToolRuntime",
    "ModelRegistry",
    "OllamaDescriptionConfig",
    "OllamaOrchestratorAgentConfig",
    "OllamaUpdaterConfig",
    "OpenAIDescriptionConfig",
    "OpenAIOrchestratorAgentConfig",
    "OpenAIUpdaterAdapter",
    "OpenAIUpdaterConfig",
    "OrchestratorAgentAdapter",
    "OrchestratorAgentConfig",
    "OrchestratorAgentModel",
    "ProviderFunctionCall",
    "ProviderToolFeedback",
    "PromptUpdateProviderResponse",
    "PromptUpdateRequest",
    "PromptUpdateResult",
    "PromptUpdaterAdapter",
    "PromptUpdaterProvider",
    "UpdaterContextTarget",
    "UpdaterConfig",
    "UpdaterOutputError",
    "UpdaterRole",
    "UpdaterTask",
    "UpdaterTaskRegistry",
    "WorldPredictionAdapter",
    "WorldPredictionModel",
    "HuggingFaceUpdaterAdapter",
    "OllamaUpdaterAdapter",
    "WorldGameContextUpdateInput",
    "WorldGameContextUpdaterModel",
]
