"""Updater model package for role P."""

from face_of_agi.models.updater.adapter import (
    PromptUpdaterAdapter,
    PromptUpdaterProvider,
    UpdaterOutputError,
    load_updater_instructions,
    parse_updated_context_output,
    updater_instruction_path,
)
from face_of_agi.models.updater.config import (
    OllamaUpdaterConfig,
    OpenAIUpdaterConfig,
    UpdaterConfig,
)
from face_of_agi.models.updater.contracts import (
    AgentGameContextUpdateInput,
    AgentProgressFeedback,
    AgentGameContextUpdaterModel,
    ContextSegment,
    GeneralKnowledgeUpdateInput,
    GeneralKnowledgeUpdaterModel,
    GoalGameContextUpdateInput,
    GoalGameContextUpdaterModel,
    PromptImage,
    PromptUpdateProviderResponse,
    PromptUpdateRequest,
    PromptUpdateResult,
    UpdaterContextTarget,
    UpdaterRole,
    UpdaterTask,
    UpdaterTaskRegistry,
    WorldGameContextUpdateInput,
    WorldGameContextUpdaterModel,
    updated_context_json_schema,
)

__all__ = [
    "AgentGameContextUpdateInput",
    "AgentProgressFeedback",
    "AgentGameContextUpdaterModel",
    "ContextSegment",
    "GeneralKnowledgeUpdateInput",
    "GeneralKnowledgeUpdaterModel",
    "GoalGameContextUpdateInput",
    "GoalGameContextUpdaterModel",
    "OllamaUpdaterConfig",
    "OpenAIUpdaterConfig",
    "PromptImage",
    "PromptUpdateProviderResponse",
    "PromptUpdateRequest",
    "PromptUpdateResult",
    "PromptUpdaterAdapter",
    "PromptUpdaterProvider",
    "UpdaterContextTarget",
    "UpdaterConfig",
    "UpdaterOutputError",
    "UpdaterRole",
    "UpdaterTask",
    "UpdaterTaskRegistry",
    "WorldGameContextUpdateInput",
    "WorldGameContextUpdaterModel",
    "load_updater_instructions",
    "parse_updated_context_output",
    "updated_context_json_schema",
    "updater_instruction_path",
]
