"""Updater model package for role P."""

from face_of_agi.models.updater.adapter import (
    PromptUpdaterAdapter,
    PromptUpdaterProvider,
    UpdaterOutputError,
    load_updater_instructions,
    parse_agent_game_updated_context_output,
    parse_updated_context_output,
    updater_instruction_path,
)
from face_of_agi.models.updater.config import (
    OllamaUpdaterConfig,
    OpenAIUpdaterConfig,
    UpdaterConfig,
    VLLMUpdaterConfig,
)
from face_of_agi.models.updater.contracts import (
    AGENT_GAME_CONTEXT_KEYS,
    AGENT_GAME_CONTEXT_MAX_CHARS,
    AgentContextRevisionFeedback,
    AgentGameContextUpdateInput,
    AgentProgressFeedback,
    AgentGameContextUpdaterModel,
    ContextSegment,
    GeneralKnowledgeUpdateInput,
    GeneralKnowledgeUpdaterModel,
    PromptImage,
    PromptUpdateProviderResponse,
    PromptUpdateRequest,
    PromptUpdateResult,
    UpdaterContextTarget,
    UpdaterRole,
    UpdaterTask,
    UpdaterTaskRegistry,
    agent_game_updated_context_json_schema,
    updated_context_json_schema,
)

__all__ = [
    "AgentContextRevisionFeedback",
    "AgentGameContextUpdateInput",
    "AgentProgressFeedback",
    "AgentGameContextUpdaterModel",
    "AGENT_GAME_CONTEXT_KEYS",
    "AGENT_GAME_CONTEXT_MAX_CHARS",
    "ContextSegment",
    "GeneralKnowledgeUpdateInput",
    "GeneralKnowledgeUpdaterModel",
    "OllamaUpdaterConfig",
    "OpenAIUpdaterConfig",
    "PromptImage",
    "PromptUpdateProviderResponse",
    "PromptUpdateRequest",
    "PromptUpdateResult",
    "PromptUpdaterAdapter",
    "PromptUpdaterProvider",
    "UpdaterContextTarget",
    "UpdaterConfig",
    "UpdaterOutputError",
    "UpdaterRole",
    "UpdaterTask",
    "UpdaterTaskRegistry",
    "VLLMUpdaterConfig",
    "load_updater_instructions",
    "parse_agent_game_updated_context_output",
    "parse_updated_context_output",
    "agent_game_updated_context_json_schema",
    "updated_context_json_schema",
    "updater_instruction_path",
]
