"""Build the ARC Prize 2026 Kaggle RTX 6000 debug notebook."""

from __future__ import annotations

import base64
import argparse
from io import BytesIO
import json
from pathlib import Path
import re
import subprocess
import sys
import tarfile
from textwrap import dedent

ROOT = Path(__file__).resolve().parents[2]
KAGGLE_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from kaggle_env import kaggle_dataset_sources, kaggle_owner  # noqa: E402

NOTEBOOK_PATH = KAGGLE_ROOT / "debug-notebooks" / "debug.ipynb"
METADATA_PATH = KAGGLE_ROOT / "debug-notebooks" / "kernel-metadata.json"
METADATA_TEMPLATE_PATH = (
    KAGGLE_ROOT / "debug-notebooks" / "kernel-metadata.template.json"
)

ACCELERATOR = "rtx6000"
_ACCELERATORS = {
    "rtx6000": {"name": "NvidiaRtxPro6000", "gpu": True},
}
DEBUG_KERNEL_TITLE_PREFIX = "Debug"
DEBUG_KERNEL_TITLE_MAX_LENGTH = 48
DEBUG_KERNEL_COMMIT_LENGTH = 8

DEFAULT_CONFIG_RELATIVE_PATH = (
    "src/face_of_agi/runtime/configs/vllm/"
    "vllm_rtx6000_qwen36_35b_fp8_debug.yaml"
)
PROJECT_DIR = "/kaggle/working/face-of-agi"
DATABASE_PATH = "/kaggle/working/runs/memory.sqlite"
WHEELHOUSE_DATASET_SLUG = "face-of-agi-wheelhouse"
PUBLIC_GAMES_DATASET_SLUG = "face-of-agi-public-games"
COMPETITION_SLUG = "arc-prize-2026-arc-agi-3"
DEFAULT_MODEL_DATASET_SLUG = "face-of-agi-qwen36-35b-fp8-weights"
CONFIG_PUBLIC_GAMES_PATH = f"/kaggle/input/{PUBLIC_GAMES_DATASET_SLUG}"
VLLM_VERSION = "0.19.1"
RUNTIME_PACKAGES = (
    "arc-agi",
    "python-dotenv",
    "pyyaml",
    "rich",
    "openai",
    "pandas",
    "pyarrow",
)
VLLM_STACK_PACKAGES = (
    "compressed-tensors==0.15.0.1",
    "flashinfer-python==0.6.6",
    "quack-kernels==0.4.1",
    "torch-c-dlpack-ext",
    f"vllm=={VLLM_VERSION}",
    "xgrammar==0.2.1",
)
VLLM_TORCH_DEPENDENCY_PACKAGES = (
    "apache-tvm-ffi>=0.1.2",
    "click",
    "cloudpickle",
    "cuda-tile",
    "einops",
    "loguru",
    "ml-dtypes",
    "ninja",
    "numpy>=1.23.5",
    "nvidia-cudnn-frontend>=1.13.0",
    "nvidia-cutlass-dsl==4.6.0.dev0",
    "nvidia-ml-py",
    "packaging>=24.2",
    "psutil",
    "pydantic>=2.0",
    "requests",
    "setuptools",
    "tabulate",
    "tqdm>=4.62.3",
    "transformers>=4.45.0",
    "typing-extensions>=4.10.0",
    "z3-solver<4.15.5,>=4.13.0",
)


def code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "metadata": {"trusted": True},
        "outputs": [],
        "execution_count": None,
        "source": source,
    }


def markdown_cell(source: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source}


def build(
    source_archive_b64: str | None = None,
    *,
    config_relative_path: str = DEFAULT_CONFIG_RELATIVE_PATH,
    model_dataset_slug: str = DEFAULT_MODEL_DATASET_SLUG,
) -> dict:
    """Return the debug notebook document."""

    if ACCELERATOR not in _ACCELERATORS:
        raise SystemExit(f"Unknown ACCELERATOR={ACCELERATOR!r}")

    archive_b64 = source_archive_b64 or _source_archive_b64()
    accel = _ACCELERATORS[ACCELERATOR]
    return {
        "metadata": {
            "kernelspec": {
                "language": "python",
                "display_name": "Python 3",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "mimetype": "text/x-python",
                "file_extension": ".py",
                "pygments_lexer": "ipython3",
            },
            "kaggle": {
                "accelerator": accel["name"],
                "isInternetEnabled": False,
                "isGpuEnabled": accel["gpu"],
                "language": "python",
                "sourceType": "notebook",
            },
        },
        "nbformat_minor": 4,
        "nbformat": 4,
        "cells": [
            markdown_cell(
                "# FACE-OF-AGI ARC Prize 2026 RTX 6000 Debug\n\n"
                "Generated by `kaggle/scripts/build_debug_notebook.py`."
            ),
            _install_cell(),
            _write_source_cell(archive_b64),
            _run_debug_cell(
                config_relative_path=config_relative_path,
                model_dataset_slug=model_dataset_slug,
            ),
        ],
    }


def _install_cell() -> dict:
    return code_cell(
        dedent(
            f"""\
            import subprocess
            import sys
            import zipfile
            from pathlib import Path
            from pip._vendor.packaging.requirements import Requirement
            from pip._vendor.packaging.utils import canonicalize_name

            __KAGGLE_INPUT_HELPERS__

            wheelhouse_input = kaggle_dataset_input({WHEELHOUSE_DATASET_SLUG!r})
            competition_wheels = (
                kaggle_competition_input({COMPETITION_SLUG!r}) / "arc_agi_3_wheels"
            )

            def pip_install(packages, *, no_deps=False):
                command = [
                    sys.executable,
                    "-m",
                    "pip",
                    "install",
                    "--no-index",
                    "--find-links",
                    str(competition_wheels),
                    "--find-links",
                    str(wheelhouse_input),
                ]
                if no_deps:
                    command.append("--no-deps")
                subprocess.check_call(command + list(packages))

            def wheel_for(distribution, version=None):
                normalized = canonicalize_name(distribution).replace("-", "_")
                pattern = (
                    f"{{normalized}}-*.whl"
                    if version is None
                    else f"{{normalized}}-{{version}}*.whl"
                )
                matches = sorted(wheelhouse_input.glob(pattern))
                if not matches:
                    raise FileNotFoundError(
                        f"Could not find {{distribution}} wheel in {{wheelhouse_input}}"
                    )
                return matches[-1]

            def vllm_dependency_requirements():
                skipped = {{
                    "torch",
                    "torchaudio",
                    "torchvision",
                    "triton",
                    "vllm",
                    "cuda-toolkit",
                    "compressed-tensors",
                    "flashinfer-python",
                    "quack-kernels",
                    "tilelang",
                    "tokenspeed-mla",
                    "torch-c-dlpack-ext",
                    "xgrammar",
                }}
                with zipfile.ZipFile(wheel_for("vllm", {VLLM_VERSION!r})) as wheel:
                    metadata_name = next(
                        name
                        for name in wheel.namelist()
                        if name.endswith(".dist-info/METADATA")
                    )
                    metadata = wheel.read(metadata_name).decode("utf-8")
                requirements = []
                for line in metadata.splitlines():
                    if not line.startswith("Requires-Dist: "):
                        continue
                    requirement = Requirement(line.removeprefix("Requires-Dist: "))
                    if canonicalize_name(requirement.name) in skipped:
                        continue
                    if requirement.marker is not None and not requirement.marker.evaluate({{"extra": ""}}):
                        continue
                    requirements.append(str(requirement))
                return requirements

            pip_install({RUNTIME_PACKAGES!r})
            pip_install({VLLM_TORCH_DEPENDENCY_PACKAGES!r})
            pip_install(vllm_dependency_requirements())
            pip_install({VLLM_STACK_PACKAGES!r}, no_deps=True)
            """
        ).replace("__KAGGLE_INPUT_HELPERS__", _kaggle_input_helpers())
    )


def _write_source_cell(archive_b64: str) -> dict:
    return code_cell(
        "import base64, io, pathlib, shutil, sys, tarfile\n"
        f"PROJECT_DIR = pathlib.Path({PROJECT_DIR!r})\n"
        "if PROJECT_DIR.exists():\n"
        "    shutil.rmtree(PROJECT_DIR)\n"
        "PROJECT_DIR.mkdir(parents=True, exist_ok=True)\n"
        f"payload = {archive_b64!r}\n"
        "with tarfile.open(fileobj=io.BytesIO(base64.b64decode(payload)), "
        "mode='r:gz') as tar:\n"
        "    tar.extractall(PROJECT_DIR, filter='data')\n"
        "sys.path.insert(0, str(PROJECT_DIR / 'src'))\n"
        "print(f'Wrote FACE-OF-AGI source to {PROJECT_DIR}')"
    )


def _run_debug_cell(
    *,
    config_relative_path: str,
    model_dataset_slug: str,
) -> dict:
    config_model_path = f"/kaggle/input/{model_dataset_slug}"
    return code_cell(
        dedent(
            f"""\
            import os
            import shutil
            import subprocess
            import sys
            import time
            import urllib.error
            import urllib.request
            import zipfile
            from pathlib import Path

            project_dir = Path({PROJECT_DIR!r})
            config_path = project_dir / {config_relative_path!r}
            database_path = Path({DATABASE_PATH!r})
            database_path.parent.mkdir(parents=True, exist_ok=True)
            __KAGGLE_INPUT_HELPERS__
            public_games_input = kaggle_dataset_input({PUBLIC_GAMES_DATASET_SLUG!r})
            model_input = kaggle_dataset_input({model_dataset_slug!r})
            public_game_catalog_path = public_games_input / "local_games.json"
            public_environments_dir = public_games_input / "environment_files"
            if not public_environments_dir.exists():
                public_environments_zip = public_games_input / "environment_files.zip"
                if not public_environments_zip.exists():
                    raise FileNotFoundError(
                        "Could not find public game environment files at "
                        f"{{public_environments_dir}} or {{public_environments_zip}}"
                    )
                extract_root = Path("/kaggle/working/public-games")
                if extract_root.exists():
                    shutil.rmtree(extract_root)
                extract_root.mkdir(parents=True, exist_ok=True)
                with zipfile.ZipFile(public_environments_zip) as archive:
                    archive.extractall(extract_root)
                public_environments_dir = extract_root / "environment_files"
                if not public_environments_dir.exists():
                    public_environments_dir = extract_root
            if not public_game_catalog_path.exists():
                raise FileNotFoundError(f"Missing public game catalog: {{public_game_catalog_path}}")
            if not any(public_environments_dir.rglob("metadata.json")):
                raise FileNotFoundError(
                    "Public game environment files were not found under "
                    f"{{public_environments_dir}}"
                )
            config_text = (
                config_path.read_text(encoding="utf-8")
                .replace(
                    {(CONFIG_PUBLIC_GAMES_PATH + "/local_games.json")!r},
                    str(public_game_catalog_path),
                )
                .replace(
                    {(CONFIG_PUBLIC_GAMES_PATH + "/environment_files")!r},
                    str(public_environments_dir),
                )
                .replace({CONFIG_PUBLIC_GAMES_PATH!r}, str(public_games_input))
                .replace({config_model_path!r}, str(model_input))
            )
            runtime_config_path = Path("/kaggle/working/runtime_config.yaml")
            runtime_config_path.write_text(config_text, encoding="utf-8")
            os.environ.update({{
                "ENVIRONMENTS_DIR": str(public_environments_dir),
                "RECORDINGS_DIR": "/kaggle/working/recordings",
                "MPLBACKEND": "agg",
                "VLLM_API_KEY": "EMPTY",
                "VLLM_DISABLE_LOG_LOGO": "1",
                "VLLM_LOGGING_LEVEL": "ERROR",
            }})
            source_dir = str(project_dir / "src")
            existing_pythonpath = os.environ.get("PYTHONPATH")
            os.environ["PYTHONPATH"] = (
                source_dir
                if not existing_pythonpath
                else source_dir + os.pathsep + existing_pythonpath
            )
            sys.path.insert(0, source_dir)

            from face_of_agi.runtime.vllm_server import (
                vllm_server_command,
                vllm_server_config_from_config_text,
            )

            vllm_config = vllm_server_config_from_config_text(
                config_text
            )
            if vllm_config is None:
                raise RuntimeError("Kaggle debug config does not define a vLLM server")
            command = list(vllm_server_command(vllm_config))
            print("Starting vLLM:", " ".join(command))
            process = subprocess.Popen(command, cwd=str(project_dir))

            def wait_for_vllm() -> None:
                deadline = time.monotonic() + 900
                url = f"{{vllm_config.base_url}}/models"
                while time.monotonic() < deadline:
                    if process.poll() is not None:
                        raise RuntimeError(
                            "vLLM exited before becoming ready with return code "
                            f"{{process.returncode}}"
                        )
                    try:
                        api_key = os.environ.get("VLLM_API_KEY", "")
                        request = urllib.request.Request(
                            url,
                            headers={{"Authorization": f"Bearer {{api_key}}"}},
                        )
                        with urllib.request.urlopen(request, timeout=5) as response:
                            if 200 <= response.status < 500:
                                return
                    except (TimeoutError, urllib.error.URLError):
                        time.sleep(2)
                raise RuntimeError("vLLM did not become ready inside Kaggle")

            try:
                wait_for_vllm()
                subprocess.check_call(
                    [
                        sys.executable,
                        "-m",
                        "face_of_agi.runtime.shell",
                        "--config",
                        str(runtime_config_path),
                        "--database",
                        str(database_path),
                        "--debug-keep-all-m-states",
                    ],
                    cwd=str(project_dir),
                )
            finally:
                process.terminate()
                try:
                    process.wait(timeout=30)
                except subprocess.TimeoutExpired:
                    process.kill()

            for sqlite_path in sorted(database_path.parent.glob("*.sqlite")):
                print(f"debug sqlite: {{sqlite_path}}")
            """
        ).replace("__KAGGLE_INPUT_HELPERS__", _kaggle_input_helpers())
    )


def _kaggle_input_helpers() -> str:
    return dedent(
        """\
        def _latest_version(paths):
            def key(path):
                if path.name.isdigit():
                    return (0, int(path.name))
                return (1, path.name)

            matches = [path for path in paths if path.exists()]
            if not matches:
                return None
            return sorted(matches, key=key)[-1]


        def _input_root_listing():
            root = Path("/kaggle/input")
            if not root.exists():
                return "<missing /kaggle/input>"
            paths = list(sorted(root.iterdir()))
            datasets_root = root / "datasets"
            if datasets_root.exists():
                paths.extend(sorted(datasets_root.glob("*")))
                paths.extend(sorted(datasets_root.glob("*/*")))
                paths.extend(sorted(datasets_root.glob("*/*/versions/*")))
            return "\\n".join(str(path) for path in paths)


        def _dataset_candidate(path):
            if not path.exists():
                return None
            version = _latest_version((path / "versions").glob("*"))
            return version if version is not None else path


        def kaggle_dataset_input(slug):
            datasets_root = Path("/kaggle/input/datasets")
            for candidate in (
                Path("/kaggle/input") / slug,
                datasets_root / slug,
            ):
                resolved = _dataset_candidate(candidate)
                if resolved is not None:
                    return resolved
            for candidate in sorted(datasets_root.glob(f"*/{slug}")):
                resolved = _dataset_candidate(candidate)
                if resolved is not None:
                    return resolved
            direct_version = _latest_version(datasets_root.glob(f"{slug}/versions/*"))
            if direct_version is not None:
                return direct_version
            nested_version = _latest_version(
                datasets_root.glob(f"*/{slug}/versions/*")
            )
            if nested_version is not None:
                return nested_version
            for candidate in sorted(datasets_root.rglob(slug)):
                resolved = _dataset_candidate(candidate)
                if resolved is not None:
                    return resolved
            raise FileNotFoundError(
                f"Could not resolve Kaggle dataset {slug!r}. "
                f"/kaggle/input contains:\\n{_input_root_listing()}"
            )


        def kaggle_competition_input(slug):
            for candidate in (
                Path("/kaggle/input/competitions") / slug,
                Path("/kaggle/input") / slug,
            ):
                if candidate.exists():
                    return candidate
            raise FileNotFoundError(
                f"Could not resolve Kaggle competition {slug!r}. "
                f"/kaggle/input contains:\\n{_input_root_listing()}"
            )

        """
    )


def _source_archive_b64() -> str:
    """Return a base64 tarball with only files needed by the Kaggle runtime."""

    buffer = BytesIO()
    with tarfile.open(fileobj=buffer, mode="w:gz") as tar:
        for relative_path in (
            "src/face_of_agi",
            "pyproject.toml",
        ):
            path = ROOT / relative_path
            if not path.exists():
                raise SystemExit(f"missing required source path: {relative_path}")
            tar.add(path, arcname=relative_path, filter=_runtime_tar_filter)
    return base64.b64encode(buffer.getvalue()).decode("ascii")


def _runtime_tar_filter(info: tarfile.TarInfo) -> tarfile.TarInfo | None:
    parts = set(Path(info.name).parts)
    if "__pycache__" in parts or info.name.endswith((".pyc", ".pyo")):
        return None
    info.uid = 0
    info.gid = 0
    info.uname = ""
    info.gname = ""
    return info


def _git_output(*args: str) -> str:
    try:
        result = subprocess.run(
            ("git", *args),
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        stderr = exc.stderr.strip()
        detail = f": {stderr}" if stderr else ""
        raise SystemExit(f"git {' '.join(args)} failed{detail}") from exc
    return result.stdout.strip()


def _current_debug_kernel_identity(
    owner: str,
    *,
    kernel_title_suffix: str = "",
) -> tuple[str, str]:
    branch_name = _current_branch_name()
    commit_id = _git_output(
        "rev-parse",
        f"--short={DEBUG_KERNEL_COMMIT_LENGTH}",
        "HEAD",
    )
    return _debug_kernel_identity(
        owner,
        branch_name,
        commit_id,
        kernel_title_suffix=kernel_title_suffix,
    )


def _debug_kernel_identity(
    owner: str,
    branch_name: str,
    commit_id: str,
    *,
    kernel_title_suffix: str = "",
) -> tuple[str, str]:
    owner = owner.strip()
    if not owner:
        raise SystemExit("debug notebook kernel metadata id is missing an owner")
    branch_slug = _metadata_slug(branch_name)
    commit_slug = _metadata_slug(commit_id)
    suffix_slug = (
        _metadata_slug(kernel_title_suffix) if kernel_title_suffix.strip() else ""
    )
    branch_slug = _debug_kernel_branch_slug(
        branch_slug,
        commit_slug,
        kernel_title_suffix=suffix_slug,
    )
    title_parts = [DEBUG_KERNEL_TITLE_PREFIX]
    if suffix_slug:
        title_parts.append(suffix_slug)
    title_parts.extend((branch_slug, commit_slug))
    title = " ".join(title_parts)
    kernel_slug = _metadata_slug(title)
    return f"{owner}/{kernel_slug}", title


def _current_branch_name() -> str:
    branch_name = _git_output("branch", "--show-current")
    if branch_name:
        return branch_name

    refs = _git_output(
        "for-each-ref",
        "--format=%(refname:short)",
        "--points-at",
        "HEAD",
        "refs/heads",
        "refs/remotes/origin",
    ).splitlines()
    for ref in refs:
        if ref and not ref.startswith("origin/"):
            return ref
    for ref in refs:
        if ref.startswith("origin/") and ref != "origin/HEAD":
            return ref.removeprefix("origin/")

    raise SystemExit("debug notebook kernel id requires a named git branch")


def _debug_kernel_branch_slug(
    branch_slug: str,
    commit_slug: str,
    *,
    kernel_title_suffix: str = "",
) -> str:
    fixed_parts = [DEBUG_KERNEL_TITLE_PREFIX]
    if kernel_title_suffix:
        fixed_parts.append(kernel_title_suffix)
    fixed_parts.append(commit_slug)
    max_branch_length = (
        DEBUG_KERNEL_TITLE_MAX_LENGTH
        - sum(len(part) for part in fixed_parts)
        - len(fixed_parts)
    )
    if max_branch_length < 1:
        raise SystemExit("debug notebook kernel title prefix is too long")
    if len(branch_slug) <= max_branch_length:
        return branch_slug

    shortened_slug = branch_slug[:max_branch_length].strip("-")
    if not shortened_slug:
        raise SystemExit(f"cannot shorten debug kernel branch slug {branch_slug!r}")
    return shortened_slug


def _metadata_slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    if not slug:
        raise SystemExit(f"cannot derive Kaggle slug from {value!r}")
    return slug


def _metadata_owner(metadata: dict) -> str:
    kernel_id = metadata.get("id")
    if not isinstance(kernel_id, str) or "/" not in kernel_id:
        raise SystemExit("debug notebook kernel metadata id must be owner/slug")
    owner = kernel_id.split("/", 1)[0].strip()
    if not owner:
        raise SystemExit("debug notebook kernel metadata id is missing an owner")
    return owner


def _dataset_source_slugs(model_dataset_slug: str) -> tuple[str, str, str]:
    return (
        WHEELHOUSE_DATASET_SLUG,
        PUBLIC_GAMES_DATASET_SLUG,
        model_dataset_slug,
    )


def _sync_metadata(
    *,
    model_dataset_slug: str = DEFAULT_MODEL_DATASET_SLUG,
    kernel_title_suffix: str = "",
) -> dict:
    if not METADATA_TEMPLATE_PATH.exists():
        raise SystemExit(
            f"missing Kaggle debug kernel metadata template: {METADATA_TEMPLATE_PATH}"
        )

    meta = json.loads(METADATA_TEMPLATE_PATH.read_text(encoding="utf-8"))
    meta["id"], meta["title"] = _current_debug_kernel_identity(
        kaggle_owner(),
        kernel_title_suffix=kernel_title_suffix,
    )
    meta["enable_gpu"] = _ACCELERATORS[ACCELERATOR]["gpu"]
    meta["enable_internet"] = False
    meta["dataset_sources"] = kaggle_dataset_sources(
        _dataset_source_slugs(model_dataset_slug)
    )
    meta["model_sources"] = []
    METADATA_PATH.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    return meta


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build the ARC Prize 2026 Kaggle RTX 6000 debug notebook.",
    )
    parser.add_argument("--metadata-only", action="store_true")
    parser.add_argument("--config-relative-path", default=DEFAULT_CONFIG_RELATIVE_PATH)
    parser.add_argument("--model-dataset-slug", default=DEFAULT_MODEL_DATASET_SLUG)
    parser.add_argument("--kernel-title-suffix", default="")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = _parse_args(sys.argv[1:] if argv is None else argv)
    if args.metadata_only:
        meta = _sync_metadata(
            model_dataset_slug=args.model_dataset_slug,
            kernel_title_suffix=args.kernel_title_suffix,
        )
        print(
            "[build_debug_notebook] Synced "
            f"{_display_path(METADATA_PATH)} as {meta['id']}"
        )
        return

    NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    NOTEBOOK_PATH.write_text(
        json.dumps(
            build(
                config_relative_path=args.config_relative_path,
                model_dataset_slug=args.model_dataset_slug,
            ),
            indent=1,
        ),
        encoding="utf-8",
    )
    print(f"[build_debug_notebook] Wrote {_display_path(NOTEBOOK_PATH)}")

    meta = _sync_metadata(
        model_dataset_slug=args.model_dataset_slug,
        kernel_title_suffix=args.kernel_title_suffix,
    )
    print(
        "[build_debug_notebook] Synced "
        f"{_display_path(METADATA_PATH)} as {meta['id']}"
    )


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


if __name__ == "__main__":
    main()
