"""Build the ARC Prize 2026 Kaggle RTX 6000 debug notebook."""

from __future__ import annotations

import argparse
import base64
from io import BytesIO
import json
from pathlib import Path
import re
import subprocess
import sys
import tarfile
from textwrap import dedent

ROOT = Path(__file__).resolve().parents[2]
KAGGLE_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from kaggle_env import kaggle_dataset_sources, kaggle_owner  # noqa: E402

NOTEBOOK_PATH = KAGGLE_ROOT / "debug-notebooks" / "debug.ipynb"
METADATA_PATH = KAGGLE_ROOT / "debug-notebooks" / "kernel-metadata.json"
METADATA_TEMPLATE_PATH = (
    KAGGLE_ROOT / "debug-notebooks" / "kernel-metadata.template.json"
)

ACCELERATOR = "rtx6000"
_ACCELERATORS = {
    "rtx6000": {"name": "NvidiaRtxPro6000", "gpu": True},
}
DEBUG_KERNEL_TITLE_PREFIX = "FOA"
DEBUG_KERNEL_COMMIT_LENGTH = 8

CONFIG_RELATIVE_PATH = (
    "src/face_of_agi/runtime/configs/kaggle_debug_transformers.yaml"
)
PROJECT_DIR = "/kaggle/working/face-of-agi"
DATABASE_PATH = "/kaggle/working/runs/memory.sqlite"
WHEELHOUSE_DATASET_SLUG = "face-of-agi-transformers-wheelhouse"
PUBLIC_GAMES_DATASET_SLUG = "face-of-agi-public-games"
COMPETITION_SLUG = "arc-prize-2026-arc-agi-3"
MODEL_DATASET_SLUG = "face-of-agi-qwen36-35b-fp8-weights"
CONFIG_PUBLIC_GAMES_PATH = f"/kaggle/input/{PUBLIC_GAMES_DATASET_SLUG}"
RUNTIME_PACKAGES = (
    "arc-agi",
    "accelerate",
    "numpy",
    "pillow",
    "python-dotenv",
    "pyyaml",
    "rich",
    "pandas",
    "pyarrow",
    "safetensors",
    "torch",
    "torchvision",
    "transformers",
)


def code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "metadata": {"trusted": True},
        "outputs": [],
        "execution_count": None,
        "source": source,
    }


def markdown_cell(source: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source}


def build(
    source_archive_b64: str | None = None,
    *,
    config_relative_path: str = CONFIG_RELATIVE_PATH,
    model_dataset_slug: str = MODEL_DATASET_SLUG,
) -> dict:
    """Return the debug notebook document."""

    if ACCELERATOR not in _ACCELERATORS:
        raise SystemExit(f"Unknown ACCELERATOR={ACCELERATOR!r}")

    archive_b64 = source_archive_b64 or _source_archive_b64()
    accel = _ACCELERATORS[ACCELERATOR]
    return {
        "metadata": {
            "kernelspec": {
                "language": "python",
                "display_name": "Python 3",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "mimetype": "text/x-python",
                "file_extension": ".py",
                "pygments_lexer": "ipython3",
            },
            "kaggle": {
                "accelerator": accel["name"],
                "isInternetEnabled": False,
                "isGpuEnabled": accel["gpu"],
                "language": "python",
                "sourceType": "notebook",
            },
        },
        "nbformat_minor": 4,
        "nbformat": 4,
        "cells": [
            markdown_cell(
                "# FACE-OF-AGI ARC Prize 2026 RTX 6000 Debug\n\n"
                "Generated by `kaggle/scripts/build_debug_notebook.py`."
            ),
            _install_cell(),
            _write_source_cell(archive_b64),
            _run_debug_cell(
                config_relative_path=config_relative_path,
                model_dataset_slug=model_dataset_slug,
            ),
        ],
    }


def _install_cell() -> dict:
    return code_cell(
        dedent(
            f"""\
            import subprocess
            import sys
            from pathlib import Path

            __KAGGLE_INPUT_HELPERS__

            wheelhouse_input = kaggle_dataset_input({WHEELHOUSE_DATASET_SLUG!r})
            competition_wheels = (
                kaggle_competition_input({COMPETITION_SLUG!r}) / "arc_agi_3_wheels"
            )

            def pip_install(packages, *, no_deps=False):
                command = [
                    sys.executable,
                    "-m",
                    "pip",
                    "install",
                    "--no-index",
                    "--find-links",
                    str(competition_wheels),
                    "--find-links",
                    str(wheelhouse_input),
                ]
                if no_deps:
                    command.append("--no-deps")
                subprocess.check_call(command + list(packages))

            pip_install({RUNTIME_PACKAGES!r})
            """
        ).replace("__KAGGLE_INPUT_HELPERS__", _kaggle_input_helpers())
    )


def _write_source_cell(archive_b64: str) -> dict:
    return code_cell(
        "import base64, io, pathlib, shutil, sys, tarfile\n"
        f"PROJECT_DIR = pathlib.Path({PROJECT_DIR!r})\n"
        "if PROJECT_DIR.exists():\n"
        "    shutil.rmtree(PROJECT_DIR)\n"
        "PROJECT_DIR.mkdir(parents=True, exist_ok=True)\n"
        f"payload = {archive_b64!r}\n"
        "with tarfile.open(fileobj=io.BytesIO(base64.b64decode(payload)), "
        "mode='r:gz') as tar:\n"
        "    tar.extractall(PROJECT_DIR, filter='data')\n"
        "sys.path.insert(0, str(PROJECT_DIR / 'src'))\n"
        "print(f'Wrote FACE-OF-AGI source to {PROJECT_DIR}')"
    )


def _run_debug_cell(
    *,
    config_relative_path: str,
    model_dataset_slug: str,
) -> dict:
    return code_cell(
        dedent(
            f"""\
            import os
            import shutil
            import subprocess
            import sys
            import zipfile
            from pathlib import Path
            import yaml

            project_dir = Path({PROJECT_DIR!r})
            config_path = project_dir / {config_relative_path!r}
            database_path = Path({DATABASE_PATH!r})
            database_path.parent.mkdir(parents=True, exist_ok=True)
            __KAGGLE_INPUT_HELPERS__
            public_games_input = kaggle_dataset_input({PUBLIC_GAMES_DATASET_SLUG!r})
            model_input = kaggle_dataset_input({model_dataset_slug!r})
            public_game_catalog_path = public_games_input / "local_games.json"
            public_environments_dir = public_games_input / "environment_files"
            if not public_environments_dir.exists():
                public_environments_zip = public_games_input / "environment_files.zip"
                if not public_environments_zip.exists():
                    raise FileNotFoundError(
                        "Could not find public game environment files at "
                        f"{{public_environments_dir}} or {{public_environments_zip}}"
                    )
                extract_root = Path("/kaggle/working/public-games")
                if extract_root.exists():
                    shutil.rmtree(extract_root)
                extract_root.mkdir(parents=True, exist_ok=True)
                with zipfile.ZipFile(public_environments_zip) as archive:
                    archive.extractall(extract_root)
                public_environments_dir = extract_root / "environment_files"
                if not public_environments_dir.exists():
                    public_environments_dir = extract_root
            if not public_game_catalog_path.exists():
                raise FileNotFoundError(f"Missing public game catalog: {{public_game_catalog_path}}")
            if not any(public_environments_dir.rglob("metadata.json")):
                raise FileNotFoundError(
                    "Public game environment files were not found under "
                    f"{{public_environments_dir}}"
                )
            config_text = (
                config_path.read_text(encoding="utf-8")
                .replace(
                    {(CONFIG_PUBLIC_GAMES_PATH + "/local_games.json")!r},
                    str(public_game_catalog_path),
                )
                .replace(
                    {(CONFIG_PUBLIC_GAMES_PATH + "/environment_files")!r},
                    str(public_environments_dir),
                )
                .replace({CONFIG_PUBLIC_GAMES_PATH!r}, str(public_games_input))
            )
            config_data = yaml.safe_load(config_text)
            config_data.setdefault("agent", {{}}).setdefault("backbone", {{}})[
                "model_path"
            ] = str(model_input)
            runtime_config_path = Path("/kaggle/working/runtime_config.yaml")
            runtime_config_path.write_text(
                yaml.safe_dump(config_data, sort_keys=False),
                encoding="utf-8",
            )
            os.environ.update({{
                "ENVIRONMENTS_DIR": str(public_environments_dir),
                "RECORDINGS_DIR": "/kaggle/working/recordings",
                "MPLBACKEND": "agg",
            }})
            source_dir = str(project_dir / "src")
            existing_pythonpath = os.environ.get("PYTHONPATH")
            os.environ["PYTHONPATH"] = (
                source_dir
                if not existing_pythonpath
                else source_dir + os.pathsep + existing_pythonpath
            )
            sys.path.insert(0, source_dir)

            subprocess.check_call(
                [
                    sys.executable,
                    "-m",
                    "face_of_agi.runtime.shell",
                    "--config",
                    str(runtime_config_path),
                    "--database",
                    str(database_path),
                    "--debug-keep-all-m-states",
                ],
                cwd=str(project_dir),
            )

            for sqlite_path in sorted(database_path.parent.glob("*.sqlite")):
                print(f"debug sqlite: {{sqlite_path}}")
            """
        ).replace("__KAGGLE_INPUT_HELPERS__", _kaggle_input_helpers())
    )


def _kaggle_input_helpers() -> str:
    return dedent(
        """\
        def _latest_version(paths):
            def key(path):
                if path.name.isdigit():
                    return (0, int(path.name))
                return (1, path.name)

            matches = [path for path in paths if path.exists()]
            if not matches:
                return None
            return sorted(matches, key=key)[-1]


        def _input_root_listing():
            root = Path("/kaggle/input")
            if not root.exists():
                return "<missing /kaggle/input>"
            paths = list(sorted(root.iterdir()))
            datasets_root = root / "datasets"
            if datasets_root.exists():
                paths.extend(sorted(datasets_root.glob("*")))
                paths.extend(sorted(datasets_root.glob("*/*")))
                paths.extend(sorted(datasets_root.glob("*/*/versions/*")))
            return "\\n".join(str(path) for path in paths)


        def _dataset_candidate(path):
            if not path.exists():
                return None
            version = _latest_version((path / "versions").glob("*"))
            return version if version is not None else path


        def kaggle_dataset_input(slug):
            datasets_root = Path("/kaggle/input/datasets")
            for candidate in (
                Path("/kaggle/input") / slug,
                datasets_root / slug,
            ):
                resolved = _dataset_candidate(candidate)
                if resolved is not None:
                    return resolved
            for candidate in sorted(datasets_root.glob(f"*/{slug}")):
                resolved = _dataset_candidate(candidate)
                if resolved is not None:
                    return resolved
            direct_version = _latest_version(datasets_root.glob(f"{slug}/versions/*"))
            if direct_version is not None:
                return direct_version
            nested_version = _latest_version(
                datasets_root.glob(f"*/{slug}/versions/*")
            )
            if nested_version is not None:
                return nested_version
            for candidate in sorted(datasets_root.rglob(slug)):
                resolved = _dataset_candidate(candidate)
                if resolved is not None:
                    return resolved
            raise FileNotFoundError(
                f"Could not resolve Kaggle dataset {slug!r}. "
                f"/kaggle/input contains:\\n{_input_root_listing()}"
            )


        def kaggle_competition_input(slug):
            for candidate in (
                Path("/kaggle/input/competitions") / slug,
                Path("/kaggle/input") / slug,
            ):
                if candidate.exists():
                    return candidate
            raise FileNotFoundError(
                f"Could not resolve Kaggle competition {slug!r}. "
                f"/kaggle/input contains:\\n{_input_root_listing()}"
            )

        """
    )


def _source_archive_b64() -> str:
    """Return a base64 tarball with only files needed by the Kaggle runtime."""

    buffer = BytesIO()
    with tarfile.open(fileobj=buffer, mode="w:gz") as tar:
        for relative_path in (
            "src/face_of_agi",
            "pyproject.toml",
        ):
            path = ROOT / relative_path
            if not path.exists():
                raise SystemExit(f"missing required source path: {relative_path}")
            tar.add(path, arcname=relative_path, filter=_runtime_tar_filter)
    return base64.b64encode(buffer.getvalue()).decode("ascii")


def _runtime_tar_filter(info: tarfile.TarInfo) -> tarfile.TarInfo | None:
    parts = set(Path(info.name).parts)
    if "__pycache__" in parts or info.name.endswith((".pyc", ".pyo")):
        return None
    info.uid = 0
    info.gid = 0
    info.uname = ""
    info.gname = ""
    return info


def _git_output(*args: str) -> str:
    try:
        result = subprocess.run(
            ("git", *args),
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        stderr = exc.stderr.strip()
        detail = f": {stderr}" if stderr else ""
        raise SystemExit(f"git {' '.join(args)} failed{detail}") from exc
    return result.stdout.strip()


def _current_debug_kernel_identity(
    owner: str,
    *,
    kernel_title_suffix: str = "",
) -> tuple[str, str]:
    branch_name = _git_output("branch", "--show-current")
    if not branch_name:
        raise SystemExit("debug notebook kernel id requires a named git branch")
    commit_id = _git_output(
        "rev-parse",
        f"--short={DEBUG_KERNEL_COMMIT_LENGTH}",
        "HEAD",
    )
    return _debug_kernel_identity(
        owner,
        branch_name,
        commit_id,
        kernel_title_suffix=kernel_title_suffix,
    )


def _debug_kernel_identity(
    owner: str,
    branch_name: str,
    commit_id: str,
    *,
    kernel_title_suffix: str = "",
) -> tuple[str, str]:
    owner = owner.strip()
    if not owner:
        raise SystemExit("debug notebook kernel metadata id is missing an owner")
    branch_slug = _metadata_slug(branch_name)
    commit_slug = _metadata_slug(commit_id)
    title_parts = [DEBUG_KERNEL_TITLE_PREFIX]
    if kernel_title_suffix.strip():
        title_parts.append(kernel_title_suffix.strip())
    title_parts.extend((branch_slug, commit_slug))
    title = " ".join(title_parts)
    kernel_slug = _metadata_slug(title)
    return f"{owner}/{kernel_slug}", title


def _metadata_slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    if not slug:
        raise SystemExit(f"cannot derive Kaggle slug from {value!r}")
    return slug


def _metadata_owner(metadata: dict) -> str:
    kernel_id = metadata.get("id")
    if not isinstance(kernel_id, str) or "/" not in kernel_id:
        raise SystemExit("debug notebook kernel metadata id must be owner/slug")
    owner = kernel_id.split("/", 1)[0].strip()
    if not owner:
        raise SystemExit("debug notebook kernel metadata id is missing an owner")
    return owner


def _dataset_source_slugs(model_dataset_slug: str) -> tuple[str, str, str]:
    return (
        WHEELHOUSE_DATASET_SLUG,
        PUBLIC_GAMES_DATASET_SLUG,
        model_dataset_slug,
    )


def _sync_metadata(
    *,
    model_dataset_slug: str = MODEL_DATASET_SLUG,
    kernel_title_suffix: str = "",
) -> dict:
    if not METADATA_TEMPLATE_PATH.exists():
        raise SystemExit(
            f"missing Kaggle debug kernel metadata template: {METADATA_TEMPLATE_PATH}"
        )

    meta = json.loads(METADATA_TEMPLATE_PATH.read_text(encoding="utf-8"))
    meta["id"], meta["title"] = _current_debug_kernel_identity(
        kaggle_owner(),
        kernel_title_suffix=kernel_title_suffix,
    )
    meta["enable_gpu"] = _ACCELERATORS[ACCELERATOR]["gpu"]
    meta["enable_internet"] = False
    meta["dataset_sources"] = kaggle_dataset_sources(
        _dataset_source_slugs(model_dataset_slug)
    )
    meta["model_sources"] = []
    METADATA_PATH.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    return meta


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build the ARC Prize 2026 Kaggle RTX 6000 debug notebook.",
    )
    parser.add_argument("--metadata-only", action="store_true")
    parser.add_argument("--config-relative-path", default=CONFIG_RELATIVE_PATH)
    parser.add_argument("--model-dataset-slug", default=MODEL_DATASET_SLUG)
    parser.add_argument("--kernel-title-suffix", default="")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = _parse_args(sys.argv[1:] if argv is None else argv)
    if args.metadata_only:
        meta = _sync_metadata(
            model_dataset_slug=args.model_dataset_slug,
            kernel_title_suffix=args.kernel_title_suffix,
        )
        print(
            "[build_debug_notebook] Synced "
            f"{METADATA_PATH.relative_to(ROOT)} as {meta['id']}"
        )
        return

    NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    NOTEBOOK_PATH.write_text(
        json.dumps(
            build(
                config_relative_path=args.config_relative_path,
                model_dataset_slug=args.model_dataset_slug,
            ),
            indent=1,
        ),
        encoding="utf-8",
    )
    print(f"[build_debug_notebook] Wrote {NOTEBOOK_PATH.relative_to(ROOT)}")

    meta = _sync_metadata(
        model_dataset_slug=args.model_dataset_slug,
        kernel_title_suffix=args.kernel_title_suffix,
    )
    print(
        "[build_debug_notebook] Synced "
        f"{METADATA_PATH.relative_to(ROOT)} as {meta['id']}"
    )


if __name__ == "__main__":
    main()
