"""Build the ARC Prize 2026 Kaggle submission notebook."""

from __future__ import annotations

import base64
from io import BytesIO
import json
import os
from pathlib import Path
import sys
import tarfile
from textwrap import dedent, indent

ROOT = Path(__file__).resolve().parents[2]
KAGGLE_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from kaggle_env import kaggle_dataset_sources, with_kaggle_kernel_id  # noqa: E402

NOTEBOOK_PATH = KAGGLE_ROOT / "notebooks" / "submission.ipynb"
METADATA_PATH = KAGGLE_ROOT / "notebooks" / "kernel-metadata.json"

ACCELERATOR = "rtx6000"
_ACCELERATORS = {
    "rtx6000": {"name": "NvidiaRtxPro6000", "gpu": True},
}

KAGGLE_SUBMISSION_CONFIG_ENV = "FACE_OF_AGI_KAGGLE_SUBMISSION_CONFIG"
KAGGLE_MODEL_DATASET_SLUG_ENV = "FACE_OF_AGI_KAGGLE_MODEL_DATASET_SLUG"
KAGGLE_KERNEL_ID_ENV = "FACE_OF_AGI_KAGGLE_SUBMISSION_KERNEL_ID"
KAGGLE_KERNEL_TITLE_ENV = "FACE_OF_AGI_KAGGLE_SUBMISSION_KERNEL_TITLE"
DEFAULT_CONFIG_RELATIVE_PATH = "src/face_of_agi/runtime/configs/kaggle_transformers.yaml"
CONFIG_RELATIVE_PATH = os.environ.get(
    KAGGLE_SUBMISSION_CONFIG_ENV,
    DEFAULT_CONFIG_RELATIVE_PATH,
).strip() or DEFAULT_CONFIG_RELATIVE_PATH
PROJECT_DIR = "/kaggle/working/face-of-agi"
WHEELHOUSE_DATASET_SLUG = "face-of-agi-transformers-wheelhouse"
COMPETITION_SLUG = "arc-prize-2026-arc-agi-3"
DEFAULT_MODEL_DATASET_SLUG = "face-of-agi-qwen36-35b-fp8-weights"
MODEL_DATASET_SLUG = os.environ.get(
    KAGGLE_MODEL_DATASET_SLUG_ENV,
    DEFAULT_MODEL_DATASET_SLUG,
).strip() or DEFAULT_MODEL_DATASET_SLUG
DATASET_SOURCE_SLUGS = (WHEELHOUSE_DATASET_SLUG, MODEL_DATASET_SLUG)
KAGGLE_KERNEL_ID = os.environ.get(KAGGLE_KERNEL_ID_ENV, "").strip()
KAGGLE_KERNEL_TITLE = os.environ.get(KAGGLE_KERNEL_TITLE_ENV, "").strip()
RUNTIME_PACKAGES = (
    "arc-agi",
    "accelerate",
    "numpy",
    "pillow",
    "python-dotenv",
    "pyyaml",
    "rich",
    "pandas",
    "pyarrow",
    "safetensors",
    "torch",
    "torchvision",
    "transformers",
)
KAGGLE_HARD_TIMEOUT_SECONDS = 9 * 60 * 60
KAGGLE_SHUTDOWN_BUFFER_SECONDS = 10 * 60


def code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "metadata": {"trusted": True},
        "outputs": [],
        "execution_count": None,
        "source": source,
    }


def markdown_cell(source: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source}


def build(source_archive_b64: str | None = None) -> dict:
    """Return the submission notebook document."""

    if ACCELERATOR not in _ACCELERATORS:
        raise SystemExit(f"Unknown ACCELERATOR={ACCELERATOR!r}")

    archive_b64 = source_archive_b64 or _source_archive_b64()
    accel = _ACCELERATORS[ACCELERATOR]
    return {
        "metadata": {
            "kernelspec": {
                "language": "python",
                "display_name": "Python 3",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "mimetype": "text/x-python",
                "file_extension": ".py",
                "pygments_lexer": "ipython3",
            },
            "kaggle": {
                "accelerator": accel["name"],
                "isInternetEnabled": False,
                "isGpuEnabled": accel["gpu"],
                "language": "python",
                "sourceType": "notebook",
            },
        },
        "nbformat_minor": 4,
        "nbformat": 4,
        "cells": [
            markdown_cell(
                "# FACE-OF-AGI ARC Prize 2026 Submission\n\n"
                "Generated by `kaggle/scripts/build_notebook.py`."
            ),
            _install_cell(),
            _write_source_cell(archive_b64),
            _run_rerun_cell(),
            _dummy_submission_cell(),
        ],
    }


def _install_cell() -> dict:
    return code_cell(
        dedent(
            f"""\
            import subprocess
            import sys
            from pathlib import Path

            __KAGGLE_INPUT_HELPERS__

            wheelhouse_input = kaggle_dataset_input({WHEELHOUSE_DATASET_SLUG!r})
            competition_wheels = (
                kaggle_competition_input({COMPETITION_SLUG!r}) / "arc_agi_3_wheels"
            )

            def pip_install(packages, *, no_deps=False):
                command = [
                    sys.executable,
                    "-m",
                    "pip",
                    "install",
                    "--no-index",
                    "--find-links",
                    str(competition_wheels),
                    "--find-links",
                    str(wheelhouse_input),
                ]
                if no_deps:
                    command.append("--no-deps")
                subprocess.check_call(command + list(packages))

            pip_install({RUNTIME_PACKAGES!r})
            """
        ).replace("__KAGGLE_INPUT_HELPERS__", _kaggle_input_helpers())
    )


def _write_source_cell(archive_b64: str) -> dict:
    return code_cell(
        "import base64, io, pathlib, shutil, sys, tarfile\n"
        f"PROJECT_DIR = pathlib.Path({PROJECT_DIR!r})\n"
        "if PROJECT_DIR.exists():\n"
        "    shutil.rmtree(PROJECT_DIR)\n"
        "PROJECT_DIR.mkdir(parents=True, exist_ok=True)\n"
        f"payload = {archive_b64!r}\n"
        "with tarfile.open(fileobj=io.BytesIO(base64.b64decode(payload)), "
        "mode='r:gz') as tar:\n"
        "    tar.extractall(PROJECT_DIR, filter='data')\n"
        "sys.path.insert(0, str(PROJECT_DIR / 'src'))\n"
        "print(f'Wrote FACE-OF-AGI source to {PROJECT_DIR}')"
    )


def _run_rerun_cell() -> dict:
    return code_cell(
        dedent(
            f"""\
            import os
            import subprocess
            import sys
            import time
            from pathlib import Path
            import yaml

            if os.getenv("KAGGLE_IS_COMPETITION_RERUN"):
                clean_deadline_epoch_seconds = (
                    time.time()
                    + {KAGGLE_HARD_TIMEOUT_SECONDS}
                    - {KAGGLE_SHUTDOWN_BUFFER_SECONDS}
                )
                project_dir = Path({PROJECT_DIR!r})
                config_path = project_dir / {CONFIG_RELATIVE_PATH!r}
                os.environ.update({{
                    "SCHEME": "http",
                    "HOST": "gateway",
                    "PORT": "8001",
                    "ARC_API_KEY": os.environ.get("ARC_API_KEY", "test-key-123"),
                    "ARC_BASE_URL": "http://gateway:8001/",
                    "OPERATION_MODE": "competition",
                    "ENVIRONMENTS_DIR": "",
                    "RECORDINGS_DIR": "/kaggle/working/server_recording",
                    "MPLBACKEND": "agg",
                }})
                source_dir = str(project_dir / "src")
                existing_pythonpath = os.environ.get("PYTHONPATH")
                os.environ["PYTHONPATH"] = (
                    source_dir
                    if not existing_pythonpath
                    else source_dir + os.pathsep + existing_pythonpath
                )
                sys.path.insert(0, source_dir)

                __KAGGLE_INPUT_HELPERS__

                model_input = kaggle_dataset_input({MODEL_DATASET_SLUG!r})
                config_data = yaml.safe_load(config_path.read_text(encoding="utf-8"))
                config_data.setdefault("agent", {{}}).setdefault("backbone", {{}})[
                    "model_path"
                ] = str(model_input)
                runtime_config_path = Path("/kaggle/working/runtime_config.yaml")
                runtime_config_path.write_text(
                    yaml.safe_dump(config_data, sort_keys=False),
                    encoding="utf-8",
                )

                subprocess.check_call(
                    [
                        sys.executable,
                        "-m",
                        "face_of_agi.runtime.kaggle",
                        "--config",
                        str(runtime_config_path),
                        "--database-dir",
                        "/kaggle/working/runs",
                        "--tags",
                        "face-of-agi,kaggle,transformers",
                        "--deadline-epoch-seconds",
                        str(clean_deadline_epoch_seconds),
                    ],
                    cwd=str(project_dir),
                )
            """
        ).replace(
            "    __KAGGLE_INPUT_HELPERS__",
            indent(_kaggle_input_helpers(), "    "),
        )
    )


def _dummy_submission_cell() -> dict:
    return code_cell(
        dedent(
            """\
            import os
            if not os.getenv("KAGGLE_IS_COMPETITION_RERUN"):
                import pandas as pd
                submission = pd.DataFrame(
                    data=[["1_0", "1", True, 1]],
                    columns=["row_id", "game_id", "end_of_game", "score"],
                )
                submission.to_parquet(
                    "/kaggle/working/submission.parquet",
                    index=False,
                )
                submission.head()
            """
        )
    )


def _kaggle_input_helpers() -> str:
    return dedent(
        """\
        def _latest_version(paths):
            def key(path):
                if path.name.isdigit():
                    return (0, int(path.name))
                return (1, path.name)

            matches = [path for path in paths if path.exists()]
            if not matches:
                return None
            return sorted(matches, key=key)[-1]


        def _input_root_listing():
            root = Path("/kaggle/input")
            if not root.exists():
                return "<missing /kaggle/input>"
            paths = list(sorted(root.iterdir()))
            datasets_root = root / "datasets"
            if datasets_root.exists():
                paths.extend(sorted(datasets_root.glob("*")))
                paths.extend(sorted(datasets_root.glob("*/*")))
                paths.extend(sorted(datasets_root.glob("*/*/versions/*")))
            return "\\n".join(str(path) for path in paths)


        def _dataset_candidate(path):
            if not path.exists():
                return None
            version = _latest_version((path / "versions").glob("*"))
            return version if version is not None else path


        def kaggle_dataset_input(slug):
            datasets_root = Path("/kaggle/input/datasets")
            for candidate in (
                Path("/kaggle/input") / slug,
                datasets_root / slug,
            ):
                resolved = _dataset_candidate(candidate)
                if resolved is not None:
                    return resolved
            for candidate in sorted(datasets_root.glob(f"*/{slug}")):
                resolved = _dataset_candidate(candidate)
                if resolved is not None:
                    return resolved
            direct_version = _latest_version(datasets_root.glob(f"{slug}/versions/*"))
            if direct_version is not None:
                return direct_version
            nested_version = _latest_version(
                datasets_root.glob(f"*/{slug}/versions/*")
            )
            if nested_version is not None:
                return nested_version
            for candidate in sorted(datasets_root.rglob(slug)):
                resolved = _dataset_candidate(candidate)
                if resolved is not None:
                    return resolved
            raise FileNotFoundError(
                f"Could not resolve Kaggle dataset {slug!r}. "
                f"/kaggle/input contains:\\n{_input_root_listing()}"
            )


        def kaggle_competition_input(slug):
            for candidate in (
                Path("/kaggle/input/competitions") / slug,
                Path("/kaggle/input") / slug,
            ):
                if candidate.exists():
                    return candidate
            raise FileNotFoundError(
                f"Could not resolve Kaggle competition {slug!r}. "
                f"/kaggle/input contains:\\n{_input_root_listing()}"
            )

        """
    )


def _source_archive_b64() -> str:
    """Return a base64 tarball with only files needed by the Kaggle runtime."""

    buffer = BytesIO()
    with tarfile.open(fileobj=buffer, mode="w:gz") as tar:
        for relative_path in (
            "src/face_of_agi",
            "pyproject.toml",
        ):
            path = ROOT / relative_path
            if not path.exists():
                raise SystemExit(f"missing required source path: {relative_path}")
            tar.add(path, arcname=relative_path, filter=_runtime_tar_filter)
    return base64.b64encode(buffer.getvalue()).decode("ascii")


def _runtime_tar_filter(info: tarfile.TarInfo) -> tarfile.TarInfo | None:
    parts = set(Path(info.name).parts)
    if "__pycache__" in parts or info.name.endswith((".pyc", ".pyo")):
        return None
    info.uid = 0
    info.gid = 0
    info.uname = ""
    info.gname = ""
    return info


def main() -> None:
    NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    NOTEBOOK_PATH.write_text(json.dumps(build(), indent=1), encoding="utf-8")
    print(f"[build_notebook] Wrote {NOTEBOOK_PATH.relative_to(ROOT)}")

    _sync_metadata()


def _sync_metadata() -> dict | None:
    if METADATA_PATH.exists():
        meta = json.loads(METADATA_PATH.read_text(encoding="utf-8"))
        if KAGGLE_KERNEL_ID:
            meta["id"] = KAGGLE_KERNEL_ID
        else:
            meta = with_kaggle_kernel_id(meta)
        if KAGGLE_KERNEL_TITLE:
            meta["title"] = KAGGLE_KERNEL_TITLE
        meta["enable_gpu"] = _ACCELERATORS[ACCELERATOR]["gpu"]
        meta["enable_internet"] = False
        meta["dataset_sources"] = kaggle_dataset_sources(DATASET_SOURCE_SLUGS)
        meta["model_sources"] = []
        METADATA_PATH.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
        print(f"[build_notebook] Synced {_display_path(METADATA_PATH)}")
        return meta
    return None


def _display_path(path: Path) -> Path:
    if path.is_relative_to(ROOT):
        return path.relative_to(ROOT)
    return path


if __name__ == "__main__":
    main()
